Repository ablecloud-team/ablestack-cloud, pull requests merged in 2021-11, with the labels that each got.

#98 Desktop WorksVM 배포시 Userdata 변경, Cluster 상세조회 잘못된 정보 표기 수정
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterResourceModifierActionWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterStartWorker.java
  plugins/integrations/desktop-service/src/main/resources/conf/works
Labels: bug, enhancement

#100 데크스톱서비스 > 마스터 템플릿 추가 모달 수정( radio 선택 기본값 변경)
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterService.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopVersionManagerImpl.java
  ui/src/components/widgets/WorksAdminUrl.vue
  ui/src/views/desktop/AddDesktopMasterVersion.vue
Labels: enhancement

#102 가상머신 별 Wall 포털 링크 제공시 URI 기본값 세팅, 데스크톱 서비스 생성일 항목 추가반영
  api/src/main/java/org/apache/cloudstack/config/ApiServiceConfiguration.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopControllerVersion.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopMasterVersion.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopVersionManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/org/apache/cloudstack/api/response/DesktopClusterResponse.java
  plugins/integrations/desktop-service/src/main/java/org/apache/cloudstack/api/response/DesktopControllerVersionResponse.java
  plugins/integrations/desktop-service/src/main/java/org/apache/cloudstack/api/response/DesktopMasterVersionResponse.java
  ui/src/components/widgets/WorksUserUrl.vue
  ui/src/config/section/desktop.js
  ui/src/views/desktop/AddDesktopMasterVersion.vue
Labels: enhancement

#105 Desktop ControlVM - DC Userdata 변경
  plugins/integrations/desktop-service/src/main/resources/conf/dc
Labels: enhancement

#103 Desktop Cluster메뉴에서 Works 관리자 포털 링크 아이콘을 적용
  ui/src/components/widgets/WorksAdminUrl.vue
Labels: enhancement

#107 SSL Certificates 버튼이 작동하지않는 버그
  ui/src/views/infra/InfraSummary.vue
Labels: bug

#117 UEFI bootMode 추가
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
Labels: bug

#113 Desktop Service 수정사항 적용
  plugins/integrations/desktop-service/pom.xml
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterActionWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterDestroyWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterResourceModifierActionWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterStartWorker.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/config/section/compute.js
  ui/src/views/AutogenView.vue
  ui/src/views/desktop/DeployCluster.vue
Labels: bug, enhancement

#119 Desktop Plugin 수정사항 반영 및 lang 버전 변경
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/main/resources/META-INF/db/schema-AllotoBronto.sql
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterResourceModifierActionWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterStartWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopControllerVersion.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopControllerVersionVO.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopVersionManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/org/apache/cloudstack/api/command/admin/desktop/AddDesktopControllerVersionCmd.java
  plugins/integrations/desktop-service/src/main/java/org/apache/cloudstack/api/response/DesktopControllerVersionResponse.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/config/section/desktop.js
  ui/src/views/desktop/AddDesktopControllerVersion.vue
Labels: enhancement

#125 Desktop - DC VM Userdata 변경
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  plugins/integrations/desktop-service/src/main/resources/conf/dc
Labels: enhancement
