Repository ablecloud-team/ablestack-cloud, pull requests merged in 2021-12, with the labels that each got.

#127 Desktop Service - 템플릿 버전 벨리데이션 변경 및 클러스터 배포시 템플릿 버전 목록 출력 형식 변경
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopVersionManagerImpl.java
  ui/src/config/section/desktop.js
  ui/src/views/desktop/DeployCluster.vue
Labels: enhancement

#130 Desktop Service - 클러스터 배포시 네트워크 목록 중복 출력되는 오류
  ui/src/views/desktop/DeployCluster.vue
Labels: bug

#132 DesktopService - 클러스터 배포시 네트워크 선택 목록 출력시 배포된 cluster 제외하고 출력되도록 수정
  ui/src/views/desktop/DeployCluster.vue
Labels: bug, enhancement

#128 Host HA : RBD Primary Storage에 대한 Host HA 기능 제공
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHABase.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAChecker.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAMonitor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAVMActivityChecker.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckOnHostCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckVMActivityOnStoragePoolCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtFenceCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
  scripts/vm/hypervisor/kvm/kvmheartbeat_rbd.sh
  scripts/vm/hypervisor/kvm/kvmvmactivity_rbd.sh
Labels: enhancement

#134 Desktop Service - 클러스터 삭제 관련 오류 수정
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterDestroyWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterResourceModifierActionWorker.java
Labels: bug

#135 Kubernetes 네트워크 정보 출력 오류
  ui/src/views/compute/KubernetesServiceTab.vue
Labels: bug
