Repository ablecloud-team/ablestack-cloud, pull requests merged in 2022-05, with the labels that each got.

#176 Changed so that ha occurs when oobm is off
  plugins/hypervisors/kvm/src/main/java/com/cloud/ha/KVMInvestigator.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/kvm/ha/KVMHAProvider.java
Labels: enhancement

#168 Mold 소스 병합 후 한글 번역 추가반영(220426)
  .github/workflows/coverage-check.yml
  plugins/integrations/desktop-service/src/main/java/org/apache/cloudstack/api/command/user/desktop/cluster/CreateDesktopClusterCmd.java
  ui/public/config.json
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
Labels: bug, branding

#180 [mold] Zone Launch Wizard 에서 RBD Pool생성시 secret key값 누락부분 수정반영
  packaging/centos8/cloud.spec
  packaging/package.sh
  tools/apidoc/build-apidoc.sh
  tools/marvin/mvn-setup.py
  tools/marvin/pom.xml
  ui/build.js
  ui/package.json
  ui/public/config.json
  ui/src/components/page/GlobalFooter.vue
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: bug, customization

#181 [mold-build] 젠킨스 빌드시 빌드 정보 표시를 위한 정보 변경
  ui/build.js
  ui/package.json
  ui/public/config.json
  ui/src/components/page/GlobalFooter.vue
Labels: enhancement
