Repository ablecloud-team/ablestack-cloud, pull requests merged in 2022-10, with the labels that each got.

#230 스키마추가 - 파비콘관련 글로벌설정값 추가
  engine/schema/src/main/resources/META-INF/db/schema-BrontotoCerato.sql
Labels: customization

#231 [Mold] 기본스토리지 Glue block 생성시 입력 항목들의 label값 수정, glue block 으로 생성된 볼륨 삭제시 unmap 기능 추가
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/infra/AddPrimaryStorage.vue
  ui/src/views/infra/zone/ZoneWizardAddResources.vue
Labels: bug, enhancement

#232 Ablestack cerato tpm, IO_uring, host-passthrough 기본값 설정 추가
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/compute/DeployVM.vue
Labels: enhancement, customization

#233 쿠버네티스에 uuid 추가
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/dao/EngineDataCenterDaoImpl.java
  engine/schema/src/main/java/com/cloud/dc/dao/DataCenterDaoImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDao.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/controller/AutomationControllerManagerImpl.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/resource/AutomationResourceManagerImpl.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/version/AutomationVersionManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/version/DesktopVersionManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
  server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java
Labels: customization

#235 [Mold UI] i18n 한글화 적용(221006일자)
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
Labels: customization

#234 Ablestack cerato rbd unmap 안되는 문제 수정
  agent/bindir/libvirtqemuhook.in
Labels: bug

#237 [Mold API] DB업그레이드 체크 시 bronto, cerato 버전 쿼리문 순서 변경
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
Labels: bug

#239 Ablestack cerato TPM활성화 버그 수정
  api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
  api/src/main/java/com/cloud/vm/VirtualMachineProfile.java
  api/src/main/java/com/cloud/vm/VmDetailConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  ui/src/views/compute/DeployVM.vue
Labels: bug

#241 [Mold UI, API] zone 구성시 guest networks vlan 설정 값 누락 부분 수정
  api/src/main/java/com/cloud/storage/VolumeApiService.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/outofbandmanagement/ConfigureOutOfBandManagementCmd.java
  api/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagement.java
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/main/resources/META-INF/db/schema-Bronto-After.sql
  engine/schema/src/main/resources/META-INF/db/schema-Bronto-Before.sql
  engine/schema/src/main/resources/META-INF/db/schema-Cerato-After.sql
  engine/schema/src/main/resources/META-INF/db/schema-Cerato-Before.sql
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/kvm/ha/KVMHAConfig.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java
  server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/widgets/OobmUrl.vue
  ui/src/config/section/infra/hosts.js
  ui/src/views/infra/OobmTab.vue
  ui/src/views/infra/zone/AdvancedGuestTrafficForm.vue
Labels: bug

#244 [Mold agent] 호스트 nic 인터페이스명을 이용한 브릿지 생성시 문자열 제거 후 반영
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/infra/OobmTab.vue
Labels: bug

#245 가상머신 xml sysinfo 변경
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
Labels: branding

#246 [Mold agent] 게스트 네트워크 생성시 물리 nic명을 이용한 bridge명 생성관련 소스 원상복구
  agent/bindir/libvirtqemuhook.in
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  scripts/vm/network/vnet/modifyvlan.sh
Labels: bug
