Repository ablecloud-team/ablestack-cloud, pull requests merged in 2022-11, with the labels that each got.

#248 [Mold API] 221031일자 신규소스 반영 후 빌드 오류 수정
  plugins/integrations/desktop-service/src/main/resources/conf/dc
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/AblestackPrimaryDataStoreLifeCycleImpl.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java
  utils/src/main/java/com/cloud/utils/UriUtils.java
Labels: bug

#249 글로벌설정 cloud.kubernetes.cluster.network.offering 값 변경
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterService.java
Labels: bug

#250 [Mold UI] i18n 한글화 적용(221114일자)
  ui/public/locales/ko_KR.json
Labels: localization

#251 host > oobm 관리콘솔프로토콜/포트명 변경
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/outofbandmanagement/ConfigureOutOfBandManagementCmd.java
  api/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagement.java
  server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
  server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
  ui/public/config.json
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/widgets/OobmUrl.vue
  ui/src/config/section/infra/hosts.js
  ui/src/views/infra/OobmTab.vue
Labels: bug, enhancement, customization

#252 다국어적용(관리콘솔프로토콜/포트) 및 볼륨업로드 generateSignature url파라미터값 변경
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  ui/public/locales/ko_KR.json
Labels: bug

#253 Source fixes to support multiple ceph rbd monitors
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java
Labels: bug
