Repository ablecloud-team/ablestack-cloud, pull requests merged in 2022-09, with the labels that each got.

#204 [Mold API] Primary Storage 생성시 kernel RBD provider 추가 플러그인 개발
  .gitignore
  .java-version
  .python-version
  agent/bindir/libvirtqemuhook.in
  api/src/main/java/com/cloud/storage/StoragePool.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/storage/CreateStoragePoolCmd.java
  client/pom.xml
  core/src/main/java/com/cloud/agent/api/PrepareForMigrationCommand.java
  core/src/main/java/com/cloud/agent/api/StartCommand.java
  core/src/main/java/org/apache/cloudstack/storage/command/AttachCommand.java
  core/src/main/java/org/apache/cloudstack/storage/command/DettachCommand.java
  core/src/main/java/org/apache/cloudstack/storage/to/PrimaryDataStoreTO.java
  core/src/test/java/org/apache/cloudstack/api/agent/test/BackupSnapshotCommandTest.java
  core/src/test/java/org/apache/cloudstack/api/agent/test/CheckNetworkAnswerTest.java
  core/src/test/java/org/apache/cloudstack/api/agent/test/SnapshotCommandTest.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/PrimaryDataStoreInfo.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/PrimaryDataStoreParameters.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/StoragePoolVO.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/volume/datastore/PrimaryDataStoreHelper.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/PrimaryDataStoreImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/pom.xml
  plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackImageStoreLifeCycleImpl.java
  plugins/storage/volume/ablestack/pom.xml
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/driver/AblestackPrimaryDataStoreDriverImpl.java
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/AblestackPrimaryDataStoreLifeCycleImpl.java
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/provider/AblestackPrimaryDatastoreProviderImpl.java
  plugins/storage/volume/ablestack/src/main/resources/META-INF/cloudstack/storage-volume-ablestack/module.properties
  plugins/storage/volume/ablestack/src/main/resources/META-INF/cloudstack/storage-volume-ablestack/spring-storage-volume-krbd-context.xml
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/test/resources/db.properties
  ui/package-lock.json
  ui/package.json
  ui/public/assets/ablestack-logo.png
  ui/public/assets/mini-ablestack-logo.png
  ui/public/config.json
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/infra/AddPrimaryStorage.vue
  ui/src/views/infra/zone/ZoneWizardAddResources.vue
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: enhancement

#212 uuid 검색 기능 추가
  api/src/main/java/org/apache/cloudstack/acl/RoleService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/acl/ListRolesCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/RoleResponse.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/datacenter/entity/api/db/dao/EngineDataCenterDaoImpl.java
  engine/schema/src/main/java/com/cloud/dc/dao/DataCenterDaoImpl.java
  engine/schema/src/main/java/com/cloud/network/as/dao/CounterDaoImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/acl/dao/ProjectRoleDaoImpl.java
  engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDao.java
  engine/schema/src/main/java/org/apache/cloudstack/acl/dao/RoleDaoImpl.java
  plugins/metrics/src/main/java/org/apache/cloudstack/metrics/MetricsServiceImpl.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java
  server/src/main/java/com/cloud/network/vpn/RemoteAccessVpnManagerImpl.java
  server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/main/java/com/cloud/user/DomainManagerImpl.java
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
  server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java
  server/src/main/java/org/apache/cloudstack/backup/BackupManagerImpl.java
  server/src/main/java/org/apache/cloudstack/network/lb/ApplicationLoadBalancerManagerImpl.java
  ui/src/views/AutogenView.vue
Labels: enhancement

#210 Cluster메뉴 enableHA > include host 기능추가
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/ResponseGenerator.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/ha/DisableHAForClusterCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/ha/EnableHAForClusterCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/host/ListHostsCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/outofbandmanagement/ConfigureOutOfBandManagementCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/storage/UpdateStoragePoolCmd.java
  api/src/main/java/org/apache/cloudstack/ha/HAConfigManager.java
  api/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagement.java
  engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/NetworkOrchestrationService.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  engine/schema/src/main/java/com/cloud/offerings/dao/NetworkOfferingDaoImpl.java
  engine/schema/src/main/java/com/cloud/storage/DiskOfferingVO.java
  engine/schema/src/main/java/org/apache/cloudstack/ha/HAConfigVO.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  plugins/outofbandmanagement-drivers/ipmitool/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/ipmitool/IpmitoolOutOfBandManagementDriver.java
  server/src/main/java/com/cloud/api/ApiDBUtils.java
  server/src/main/java/com/cloud/api/ApiResponseHelper.java
  server/src/main/java/com/cloud/api/query/ViewResponseHelper.java
  server/src/main/java/com/cloud/configuration/Config.java
  server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
  server/src/main/java/com/cloud/storage/StorageManagerImpl.java
  server/src/main/java/org/apache/cloudstack/ha/HAManagerImpl.java
  server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
  ui/package-lock.json
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/view/ActionButton.vue
  ui/src/components/widgets/OobmUrl.vue
  ui/src/config/section/infra/clusters.js
  ui/src/config/section/infra/hosts.js
  ui/src/config/section/infra/primaryStorages.js
  ui/src/views/compute/EditVM.vue
  ui/src/views/infra/OobmTab.vue
Labels: enhancement

#211 [Mold API, UI] Primary Storage에 cephfs 플러그인 개발, SCSI 컨트롤러 xml 생성 로직 수정
  core/src/main/java/org/apache/cloudstack/storage/to/PrimaryDataStoreTO.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/provider/DefaultHostListener.java
  packaging/centos8/cloud.spec
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/AblestackPrimaryDataStoreLifeCycleImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  ui/build.js
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/page/GlobalFooter.vue
  ui/src/views/compute/KubernetesServiceTab.vue
  ui/src/views/infra/AddPrimaryStorage.vue
Labels: enhancement

#220 uuid 검색 기능 수정
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
Labels: bug

#213 localupload generateSignature url파라미터값 변경
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  server/src/main/java/org/apache/cloudstack/outofbandmanagement/OutOfBandManagementServiceImpl.java
  ui/src/views/infra/OobmTab.vue
Labels: enhancement

#218 UEFI 라이브 마이그레이션 기능 추가
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/AblestackPrimaryDataStoreLifeCycleImpl.java
  server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  ui/src/views/infra/AddPrimaryStorage.vue
Labels: enhancement

#217 Favicon 에 호스트의 상태에 따른 신호등 표시
  ui/public/index.html
  ui/src/components/header/UserMenu.vue
  ui/src/store/modules/app.js
  ui/src/store/mutation-types.js
Labels: enhancement

#216 Ablestack cerato tpm 설정 기능 추가
  agent/bindir/libvirtqemuhook.in
  api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
  api/src/main/java/com/cloud/host/Host.java
  api/src/main/java/com/cloud/vm/VirtualMachineProfile.java
  api/src/main/java/com/cloud/vm/VmDetailConstants.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  engine/orchestration/src/main/java/com/cloud/agent/manager/AgentManagerImpl.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/cloud/entity/api/VMEntityManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java
  server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/compute/DeployVM.vue
Labels: enhancement

#221 virtual router 목록조회 오류수정
  server/src/main/java/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java
Labels: bug

#219 [Mold UI] 버전 번경에 따른 UI footer 정보 변경(Cerato v3.0.0-dev), 빌드 및 테스트 오류 반영
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  core/src/main/java/com/cloud/agent/api/PrepareForMigrationCommand.java
  core/src/main/java/com/cloud/agent/api/StartCommand.java
  core/src/main/java/org/apache/cloudstack/storage/command/AttachCommand.java
  core/src/main/java/org/apache/cloudstack/storage/command/DettachCommand.java
  core/src/main/java/org/apache/cloudstack/storage/to/PrimaryDataStoreTO.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtStartCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  tools/marvin/pom.xml
  ui/build.js
  ui/public/locales/ko_KR.json
  ui/src/views/infra/zone/ZoneWizardAddResources.vue
Labels: bug, enhancement

#224 로그 ipmitool 비밀번호 삭제
  plugins/outofbandmanagement-drivers/ipmitool/src/main/java/org/apache/cloudstack/outofbandmanagement/driver/ipmitool/IpmitoolOutOfBandManagementDriver.java
  utils/src/main/java/org/apache/cloudstack/utils/process/ProcessRunner.java
Labels: enhancement

#225 [Mold-api] 신규 추가 컬럼 값 자동 업데이트 프로시저 추가
  engine/schema/src/main/resources/META-INF/db/schema-BrontotoCerato.sql
Labels: bug, enhancement

#226 [Mold-UI] zone구성 마법사를 사용하여 gluefs 기본스토리지 구성 기능 추가
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/infra/zone/ZoneWizardAddResources.vue
  ui/src/views/infra/zone/ZoneWizardLaunchZone.vue
Labels: enhancement

#227 [Mold][Genie][버그] 오토메이션 컨트롤러 대시보드 생성 시, 상태 체크 로직 변경
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/controller/actionworkers/AutomationControllerStartWorker.java
Labels: bug

#228 [Mold API] 신규소스 병합 후 빌드테스트 오류 수정(220929)
  api/src/main/java/org/apache/cloudstack/api/response/HostResponse.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  ui/public/locales/en.json
  ui/src/views/desktop/DeployCluster.vue
  ui/src/views/infra/zone/ZoneWizardAddResources.vue
Labels: enhancement, customization

#229 [Mold UI] ABLESTACK 로고 이미지 변경 및 사이즈 조정 반영
  ui/public/assets/ablestack-logo.png
  ui/public/config.json
  ui/src/components/header/Logo.vue
Labels: customization, branding
