Repository ablecloud-team/ablestack-cloud, pull requests merged in 2022-04, with the labels that each got.

#162 ASF 라이센스 정보를 작성 및 공백제거
  scripts/vm/hypervisor/kvm/kvmheartbeat_rbd.py
  scripts/vm/hypervisor/kvm/kvmvmactivity_rbd.py
Labels: bug, enhancement

#158 Mold 소스 병합 후 빌드테스트 시 오류 수정 반영
  .github/workflows/coverage-check.yml
  core/src/main/java/com/cloud/agent/api/VmStatsEntry.java
  core/src/main/java/com/cloud/agent/api/VmStatsEntryBase.java
  plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResourceTest.java
  plugins/hypervisors/simulator/src/main/java/com/cloud/agent/manager/MockVmManagerImpl.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterManagerImpl.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/test/java/com/cloud/server/StatsCollectorTest.java
  ui/public/config.json
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/page/GlobalFooter.vue
  ui/src/components/view/ActionButton.vue
  ui/src/components/view/InfoCard.vue
  ui/src/views/dashboard/CapacityDashboard.vue
Labels: bug, customization

#167 Mold 소스 병합 후 빌드테스트 시 오류 수정 반영(2022.04.25)
  .github/workflows/coverage-check.yml
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  ui/src/components/view/DetailsTab.vue
  ui/src/core/lazy_lib/icons_use.js
Labels: customization
