Repository ablecloud-team/ablestack-cloud, pull requests merged in 2022-07, with the labels that each got.

#190 Automation Service - 스키마 등록 및 Deployed Packages 기능 개선
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java
  engine/schema/src/main/resources/META-INF/db/schema-BrontotoCerato-cleanup.sql
  engine/schema/src/main/resources/META-INF/db/schema-BrontotoCerato.sql
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/controller/AutomationControllerManagerImpl.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/controller/actionworkers/AutomationControllerStartWorker.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/resource/AutomationDeployedResource.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/resource/AutomationDeployedResourceVO.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/resource/AutomationResourceManagerImpl.java
  plugins/integrations/automation-service/src/main/java/org/apache/cloudstack/api/command/user/automation/resource/AddDeployedResourceGroupCmd.java
  plugins/integrations/automation-service/src/main/java/org/apache/cloudstack/api/command/user/automation/resource/UpdateDeployedResourceGroupCmd.java
  plugins/integrations/automation-service/src/main/java/org/apache/cloudstack/api/response/AutomationDeployedResourceResponse.java
  plugins/integrations/automation-service/src/main/resources/conf/genie
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/config/section/automation.js
  ui/src/views/automation/DeployedResourceTab.vue
Labels: enhancement

#192 [Mold UI] ant design vue 버전 변경으로 데스크톱 서비스에서 사용중인 문법 수정 반영
  ui/src/views/desktop/AddDesktopControllerVersion.vue
  ui/src/views/desktop/AddDesktopMasterVersion.vue
  ui/src/views/desktop/DeployCluster.vue
  ui/src/views/offering/AddNetworkOffering.vue
Labels: enhancement, branding

#193 오토메이션컨트롤러 버그 패치 및 문구 수정
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/controller/AutomationControllerManagerImpl.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/automation/AddAutomationController.vue
  ui/src/views/automation/AutomationControllerTab.vue
Labels: bug, enhancement

#194 Automation Service - 배포된 패키지에 접근 정보 항목 추가
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  engine/schema/src/main/resources/META-INF/db/schema-BrontotoCerato.sql
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/resource/AutomationDeployedResource.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/resource/AutomationDeployedResourceVO.java
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/resource/AutomationResourceManagerImpl.java
  plugins/integrations/automation-service/src/main/java/org/apache/cloudstack/api/command/user/automation/resource/AddDeployedResourceGroupCmd.java
  plugins/integrations/automation-service/src/main/java/org/apache/cloudstack/api/command/user/automation/resource/UpdateDeployedResourceGroupCmd.java
  plugins/integrations/automation-service/src/main/java/org/apache/cloudstack/api/response/AutomationDeployedResourceResponse.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/config/section/automation.js
Labels: enhancement

#198 Automation Service - 템플릿버전메뉴, 템플릿 항목 링크추가 및 업로드유형 항목 삭제
  plugins/integrations/automation-service/src/main/java/com/cloud/automation/version/AutomationVersionManagerImpl.java
  ui/src/components/view/DetailsTab.vue
  ui/src/config/section/automation.js
Labels: enhancement

#197 [mold] 데스크톱 클러스터 배포시 works 포털 및 클라이언트 포트 변경으로 인한 데이터 변경 작업
  api/src/main/java/org/apache/cloudstack/api/command/user/config/ListCapabilitiesCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterManagerImpl.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/DesktopClusterService.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterActionWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterResourceModifierActionWorker.java
  plugins/integrations/desktop-service/src/main/java/com/cloud/desktop/cluster/actionworkers/DesktopClusterStartWorker.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/view/ActionButton.vue
  ui/src/components/widgets/WorksUrl.vue
Labels: enhancement
