Repository ablecloud-team/ablestack-cloud, pull requests merged in 2024-11, with the labels that each got.

#563 [Mold UI] 한글화 날짜 표시 포맷 변경
  ui/src/utils/date.js
Labels: customization

#564 [Mold UI] 테이블 페이징시 항목 수 표시 관련 한글화 반영
  ui/public/locales/ko_KR.json
  ui/src/components/view/AnnotationsTab.vue
  ui/src/components/view/EventsTab.vue
  ui/src/components/view/WebhookDeliveriesTab.vue
  ui/src/views/AutogenView.vue
  ui/src/views/compute/InstanceSchedules.vue
  ui/src/views/event/EventDownload.vue
  ui/src/views/infra/UsageRecords.vue
  ui/src/views/network/tungsten/TungstenNetworkTable.vue
  ui/src/views/setting/ConfigurationTable.vue
  ui/src/views/tools/ManageInstances.vue
  ui/src/views/tools/ManageVolumes.vue
Labels: customization, localization

#565 [Mold API] 볼륨 삭제 메소드의 디스크오퍼링 조회시 Null값 체크 로직 추가
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
Labels: bug

#566 [Mold API] 쿠버네티스 클러스터 생성시 호스트 리소스 정보 조회 메소드 추가
  engine/components-api/src/main/java/com/cloud/resource/ResourceManager.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
  server/src/main/java/com/cloud/api/ApiServlet.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/test/java/com/cloud/resource/MockResourceManagerImpl.java
Labels: customization

#567 [Mold API, Mold UI] 퓨어스토리지 구성에 필요한 체크항목 수정(footprint 항목 없을 경우 체크 로직 수정)
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
  plugins/storage/object/ceph/src/main/java/org/apache/cloudstack/storage/datastore/driver/CephObjectStoreDriverImpl.java
  plugins/storage/volume/flasharray/src/main/java/org/apache/cloudstack/storage/datastore/adapter/flasharray/FlashArrayAdapter.java
  ui/src/components/view/DetailsTab.vue
  ui/src/views/infra/AddObjectStorage.vue
Labels: enhancement, customization

#568 [Mold API] vmware v2v 이관 대상 기본스토리지 조회 메소드 변경(scope 항목 : "zone","cluster" 두 항목 조회)
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDao.java
  engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/PrimaryDataStoreDaoImpl.java
  server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
Labels: bug, customization

#570 [Mold API] vmware v2v nic 항목확인시 Error상황이 아닌 로그 항목 수정(레벨 변경 : error > info로 변경)
  vmware-base/src/main/java/com/cloud/hypervisor/vmware/util/VmwareHelper.java
Labels: customization

#571 대시보드 > 경고상태의 호스트 조건변경
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  ui/src/views/dashboard/CapacityDashboard.vue
Labels: bug, customization

#572 [Mold API] 20241120일자 신규소스 반영 후 빌드 오류 수정
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
Labels: bug

#574 [Mold UI] Usage, 할당 메뉴 관련 한글화 작업/ Usage 기록 조회 오류 수정(조회 날짜 전달 오류)
  ui/public/locales/ko_KR.json
  ui/src/views/infra/UsageRecords.vue
Labels: bug, customization, localization
