Repository ablecloud-team/ablestack-cloud, pull requests merged in 2024-10, with the labels that each got.

#555 [Mold APi] 호스트 디바이스 정보 조회 후 가상머신 목록 조회 시 지연 이슈 수정
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  ui/src/views/storage/HostDevicesTransfer.vue
Labels: customization

#559 [Mold UI, API] 가상머신 상세 nic탭 nic상태 업, 다운 버튼 기능 누락부분 재추가
  scripts/vm/hypervisor/kvm/nsrkvmbackup.sh
  ui/src/views/compute/wizard/OwnershipSelection.vue
  ui/src/views/infra/AddPrimaryStorage.vue
  ui/src/views/network/NicsTab.vue
Labels: customization, significant

#560 [Mold API, UI] vmware v2v 시 목적지 스토리지 조회 메소드 변경(cluster 영역 조회 > zone 영역 조회)
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
  ui/src/views/storage/CreateSharedFS.vue
Labels: bug, enhancement, customization
