Repository ablecloud-team/ablestack-cloud, pull requests merged in 2024-07, with the labels that each got.

#519 [Mold API, UI] 20240703일자 신규 소스 반영 빌드 오류 수정 및 한글화 반영
  api/src/main/java/com/cloud/vm/NicProfile.java
  api/src/main/java/com/cloud/vm/UserVmService.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java
  engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41000to41100.java
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDao.java
  engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/volume/datastore/PrimaryDataStoreHelper.java
  framework/db/src/main/java/com/cloud/utils/db/GenericDao.java
  framework/db/src/main/java/com/cloud/utils/db/GenericDaoBase.java
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/AblestackPrimaryDataStoreLifeCycleImpl.java
  server/src/main/java/com/cloud/consoleproxy/AgentBasedConsoleProxyManager.java
  server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
  server/src/test/java/com/cloud/api/query/QueryManagerImplTest.java
  ui/public/locales/ko_KR.json
Labels: bug, customization, localization

#520 [Mold API] log4j 사용방식 수정(빌드 오류 누락부분 반영)
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/BasePrimaryDataStoreLifeCycleImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckConvertInstanceCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareStorageClientCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtUnprepareStorageClientCommandWrapper.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/manager/ScaleIOSDCManagerImpl.java
Labels: bug

#517 [Mold UI] 가상머신 다중 생성 시 API 호출 후 응답 방식 수정(생성 수 만큼 UI 리프레시 되는 문제 해결)
  ui/src/views/compute/DeployVM.vue
Labels: enhancement, customization

#523 [Mold API, Agent]Glue GFS 기본스토리지 HA 기능 추가
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHABase.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAChecker.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/KVMHAMonitor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckOnHostCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckVMActivityOnStoragePoolCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtFenceCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStorageAdaptor.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStoragePool.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/kvm/ha/KVMHAConfig.java
  scripts/vm/hypervisor/kvm/kvmheartbeat_gluegfs.sh
  scripts/vm/hypervisor/kvm/kvmvmactivity_gluegfs.sh
Labels: enhancement, customization, significant

#524 [Mold API] PowerFlex 템플릿으로 시스템 vm 생성시 사이즈 0 일경우 8G 로 기본 세팅
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
Labels: customization

#525 [Mold API, UI] 기본스토리지 DefaultPrimary 일 경우 vm스냅샷명 전달되도록 수정/ 포털 UI 로컬 시간대 사용 : 기본값 true로 변경
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
  ui/src/store/modules/user.js
Labels: enhancement, customization

#507 [Mold API, UI] 가상머신 복제 기능 개발(full clone, linked clone 방식 구분)
  api/src/main/java/com/cloud/agent/api/to/DataObjectType.java
  api/src/main/java/com/cloud/storage/VolumeApiService.java
  api/src/main/java/com/cloud/storage/snapshot/SnapshotApiService.java
  api/src/main/java/com/cloud/vm/UserVmService.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/CloneVMCmd.java
  core/src/main/java/com/cloud/storage/resource/StorageProcessor.java
  core/src/main/java/com/cloud/storage/resource/StorageSubsystemCommandHandlerBase.java
  core/src/main/java/org/apache/cloudstack/storage/command/FlattenCmdAnswer.java
  core/src/main/java/org/apache/cloudstack/storage/command/FlattenCommand.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreDriver.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/ObjectInDataStoreStateMachine.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/SnapshotInfo.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/SnapshotService.java
  engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/VolumeService.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/schema/src/main/java/com/cloud/storage/SnapshotVO.java
  engine/schema/src/main/java/com/cloud/storage/VolumeVO.java
  engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDao.java
  engine/schema/src/main/java/com/cloud/storage/dao/SnapshotDaoImpl.java
  engine/schema/src/main/resources/META-INF/db/schema-Diplo-Before.sql
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotServiceImpl.java
  engine/storage/src/main/java/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java
  engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  plugins/hypervisors/ovm3/src/main/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessor.java
  plugins/hypervisors/simulator/src/main/java/com/cloud/resource/SimulatorStorageProcessor.java
  plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java
  plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java
  plugins/storage/object/ceph/src/main/java/org/apache/cloudstack/storage/datastore/driver/CephObjectStoreDriverImpl.java
  plugins/storage/object/minio/src/main/java/org/apache/cloudstack/storage/datastore/driver/MinIOObjectStoreDriverImpl.java
  plugins/storage/object/simulator/src/main/java/org/apache/cloudstack/storage/datastore/driver/SimulatorObjectStoreDriverImpl.java
  plugins/storage/volume/ablestack/src/main/java/org/apache/cloudstack/storage/datastore/driver/AblestackPrimaryDataStoreDriverImpl.java
  plugins/storage/volume/cloudbyte/src/main/java/org/apache/cloudstack/storage/datastore/driver/ElastistorPrimaryDataStoreDriver.java
  plugins/storage/volume/datera/src/main/java/org/apache/cloudstack/storage/datastore/driver/DateraPrimaryDataStoreDriver.java
  plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java
  plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
  plugins/storage/volume/nexenta/src/main/java/org/apache/cloudstack/storage/datastore/driver/NexentaPrimaryDataStoreDriver.java
  plugins/storage/volume/sample/src/main/java/org/apache/cloudstack/storage/datastore/driver/SamplePrimaryDataStoreDriverImpl.java
  plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java
  plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/driver/SolidFirePrimaryDataStoreDriver.java
  plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java
  server/src/main/java/com/cloud/configuration/Config.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/org/apache/cloudstack/snapshot/SnapshotHelper.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/config/section/compute.js
  ui/src/views/compute/CloneVM.vue
Labels: enhancement, customization, significant

#526 [Mold API, UI] 20240715일자 신규 소스 반영 빌드 오류 수정
  framework/cluster/src/main/java/com/cloud/cluster/ClusterServiceServletAdapter.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtReadyCommandWrapper.java
  ui/src/views/compute/DeployVM.vue
Labels: bug, customization

#527 [Mold API] 정지상태 가상머신의 복제 기능(Glue Block- RBD스토리지)
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: enhancement, customization

#528 [Mold ApI] 빌드 오류 수정(불필요 코드 정리)
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/public/config.json
Labels: bug

#529 [Mold API, Agent] VM 스냅샷시 호스트의 도메인 정보가 없을 경우(가상머신 정지상태) > 'freeze', 'thaw' 명령 없이 결과값 true로 전달
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtFreezeThawVMCommandWrapper.java
Labels: enhancement, customization

#531 [Mold UI, Agent] VM스냅샷 버튼 활성화(정지상태+kvm+rbd 인 조건)
  engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/SnapshotServiceImpl.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  ui/src/config/section/compute.js
Labels: bug, customization

#532 [Mold UI] 영문을 기준으로 항목 명이 변경된 부분을 한글화 파일에 반영(20240722)
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
Labels: bug, customization

#533 [Mold UI] L2 네트워크 + Secondary VLAN 선택 시 필수 파라미터 전달 오류 수정
  ui/src/views/network/CreateL2NetworkForm.vue
  ui/src/views/network/CreateSharedNetworkForm.vue
Labels: bug, customization

#534 [Mold API] ovs-pvlan 설정을 위한 쉘에서 특정 NIC 명칭 목록 추가(ens,enx,eno,enp)
  scripts/vm/network/ovs-pvlan-kvm-vm.sh
  scripts/vm/network/ovs-pvlan-vm.sh
Labels: bug, enhancement, customization

#535 [Mold API, UI] extraconfig 관련 기능 유지되도록 개선
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/src/components/view/DetailSettings.vue
Labels: customization

#536 [Mold UI] 20240731 일자 신규 소스 반영 후 한글화 작업
  ui/public/locales/ko_KR.json
Labels: localization
