Repository ablecloud-team/ablestack-cloud, pull requests merged in 2024-02, with the labels that each got.

#381 [Mold API] 글로벌 설정 기본값 변경(kvm.auto.convergence=true, drs.plan.expire.interval=15)
  api/src/main/java/org/apache/cloudstack/cluster/ClusterDrsService.java
  engine/components-api/src/main/java/com/cloud/storage/StorageManager.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: customization

#388 [Mold API] usage log 에러 코드 제거(snapshot 조회부분 - stack main소스는 제거된 상태확인)
  usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
Labels: bug

#390 [Mold API] 가상머신 복제 시 이미 존재하는 가상머신 이름체크 하는 로직 추가
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: bug

#394 [Mold API, UI] 20240207일자 신규 소스 반영 후 오류 수정 및 한글화 번역
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/integrations/automation-service/pom.xml
  plugins/integrations/desktop-service/pom.xml
  plugins/security/pom.xml
  plugins/security/src/main/java/com/cloud/security/IntegrityVerificationServiceImpl.java
  plugins/security/src/main/java/com/cloud/security/SecurityCheckServiceImpl.java
  plugins/storage/volume/ablestack/pom.xml
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java
  ui/public/locales/ko_KR.json
Labels: enhancement, customization

#404 [Mold API, UI] 기본스토리지 브라우저 삭제기능 UI 변경 및 검색기능(filesystem) 추가
  core/src/main/java/com/cloud/resource/ServerResourceBase.java
  core/src/main/java/org/apache/cloudstack/storage/command/browser/ListDataStoreObjectsCommand.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  server/src/main/java/org/apache/cloudstack/storage/browser/StorageBrowserImpl.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/infra/StorageBrowser.vue
Labels: enhancement

#413 [Mold API] 보안그룹용 오퍼링 기본값 생성시 세팅 값 수정(빌드시 오류는 없으나 jetty 구동 시 시작불가 상태)
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java
  server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: bug
