Repository ablecloud-team/ablestack-cloud, pull requests merged in 2024-05, with the labels that each got.

#460 [Mold API, UI, Agent]L2 VM IP 조회 방식 수정, vm qemu agent 버전 조회 및 가상머신 목록 표시
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/response/UserVmResponse.java
  core/src/main/java/com/cloud/agent/api/VmStatsEntryBase.java
  engine/schema/src/main/java/com/cloud/vm/VMInstanceVO.java
  engine/schema/src/main/java/org/apache/cloudstack/engine/cloud/entity/api/db/VMEntityVO.java
  engine/schema/src/main/resources/META-INF/db/schema-Diplo-Before.sql
  engine/schema/src/main/resources/META-INF/db/views/cloud.user_vm_view.sql
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/qemu/QemuCommand.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDao.java
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/vo/UserVmJoinVO.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/view/DetailsTab.vue
  ui/src/components/view/ListView.vue
  ui/src/config/section/compute.js
  ui/src/config/section/image.js
  ui/src/views/compute/InstanceTab.vue
  ui/src/views/image/UpdateISO.vue
Labels: enhancement, customization, localization, significant

#494 [Mold API, UI] 20240521일자 신규 소스 병합 후 빌드 오류 수정(이벤트 목록 조회시 정렬 버그 수정, vnf 기기 목록 조회 버그 수정)
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/RestoreVMCmd.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/server/ConfigurationServerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/org/apache/cloudstack/acl/RoleManagerImpl.java
  ui/public/locales/ko_KR.json
  ui/src/config/section/network.js
  usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
Labels: bug, customization

#495 [Mold API] 서비스,시스템,디스크 오퍼링 목록 조회시 sort순서 오류 수정
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/api/query/dao/DiskOfferingJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/dao/ServiceOfferingJoinDaoImpl.java
Labels: bug, customization

#497 [Mold API] 이벤트 목록 조회시 정렬 기능 버그 재수정
  server/src/main/java/com/cloud/event/dao/EventJoinDaoImpl.java
  ui/public/locales/ko_KR.json
Labels: bug

#496 scsi 외의 디스크타입에서 unmap 이 안되는 오류 수정
  agent/bindir/libvirtqemuhook.in
Labels: bug

#498 루트볼륨, 데이터 볼륨을 브라우저에서 생성
  api/src/main/java/com/cloud/storage/VolumeApiService.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/storage/CreateRbdImageCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/ListRbdVolumesCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/UpdateVolumeCmd.java
  core/src/main/java/com/cloud/resource/ServerResourceBase.java
  core/src/main/java/org/apache/cloudstack/storage/command/browser/CreateRbdObjectsCommand.java
  core/src/main/java/org/apache/cloudstack/storage/command/browser/ListRbdObjectsAnswer.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/views/compute/wizard/StorageRbdImageSelection.vue
  ui/src/views/infra/StorageBrowser.vue
  ui/src/views/storage/CreateVolType.vue
Labels: enhancement, customization

#502 [MOLD API, UI] VNF 어플라이언스 목록 조회 API 기능 추가(listVnfAppliances)
  .gitignore
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ListVnfAppliancesCmdByAdmin.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/ListVnfAppliancesCmd.java
  server/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateManagerImpl.java
  ui/src/config/section/image.js
  ui/src/config/section/network.js
  ui/src/views/network/VnfAppliancesTab.vue
Labels: enhancement, customization

#503 [Mold UI] 브라우저 탭 파비콘 이미지 변경
  ui/public/config.json
Labels: customization

#504 [Mold API] VNF 목록조회 기능 import 누락 반영
  server/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateManagerImpl.java
Labels: bug

#505 [Mold UI] 20240531일자 한글화 작업
  ui/public/locales/ko_KR.json
Labels: localization

#506 [Mold API] 보안기능용 글로벌 세팅 설정 값 세팅 누락 부분 반영
  server/src/main/java/com/cloud/api/ApiServer.java
Labels: bug
