Repository ablecloud-team/ablestack-cloud, pull requests merged in 2024-09, with the labels that each got.

#546 [Mold API, Agent] vmware 인스턴스 가져오기 기능 개선(rbd or sharedmountpoint 유형으로 볼륨 변경되도록 수정)
  api/src/main/java/org/apache/cloudstack/api/command/user/template/DeleteTemplateCmd.java
  engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/AncientDataMotionStrategy.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtConvertInstanceCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtPrepareForMigrationCommandWrapper.java
  server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java
  ui/src/views/plugins/ApiDocsPlugin.vue
Labels: customization

#550 [Mold] 호스트 디바이스를 가상머신에 이관(extraconfig적용)
  agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
  api/src/main/java/com/cloud/server/ManagementService.java
  api/src/main/java/com/cloud/vm/VmDetailConstants.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/outofbandmanagement/ListHostDevicesCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/ListHostDevicesResponse.java
  core/src/main/java/com/cloud/agent/api/ListHostDeviceAnswer.java
  core/src/main/java/com/cloud/agent/api/ListHostDeviceCommand.java
  core/src/main/java/com/cloud/resource/ServerResourceBase.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtlistHostDevicesCommandWrapper.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  tools/apidoc/gen_toc.py
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/config/section/compute.js
  ui/src/config/section/infra/hosts.js
  ui/src/views/infra/ListHostDevicesTab.vue
  ui/src/views/storage/HostDevicesTransfer.vue
Labels: enhancement, customization

#554 [Mold API, UI] 20240924일자 신규 소스 반영 빌드 오류 수정(한글화 포함)
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  engine/schema/src/main/resources/META-INF/db/schema-41910to42000.sql
  plugins/storage/sharedfs/storagevm/src/main/resources/conf/fsvm-init.yml
  server/src/main/java/com/cloud/api/ApiServer.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/config/section/compute.js
Labels: enhancement, customization, localization
