Repository ablecloud-team/ablestack-cloud, pull requests merged in 2024-06, with the labels that each got.

#508 [Mold UI] VNF 어플라이언스 생성 후 response jobid 조회 버그 수정
  ui/src/views/compute/DeployVnfAppliance.vue
Labels: bug

#509 [Mold API] Unmanaged 가상머신 조회시 하이퍼바이저 url 세팅 수정(qemu+tcp > qemu+ssh)
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtGetRemoteVmsCommandWrapper.java
Labels: customization

#510 [Mold API] 가상머신 생성 시 nic up = true 상태 기본값으로 설정(VRouter, 쿠버네티스 vm 생성시 nic down문제)
  api/src/main/java/com/cloud/agent/api/to/NetworkTO.java
  api/src/main/java/com/cloud/network/Network.java
  api/src/main/java/com/cloud/vm/NicProfile.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java
Labels: bug

#499 Glue이미지(Root Volume)을 이용한 가상머신 생성 기능
  api/src/main/java/com/cloud/vm/UserVmService.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/vm/DeployVMVolumeCmdByAdmin.java
  api/src/main/java/org/apache/cloudstack/api/command/user/vm/DeployVMVolumeCmd.java
  engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java
  engine/api/src/main/java/org/apache/cloudstack/engine/orchestration/service/VolumeOrchestrationService.java
  engine/api/src/main/java/org/apache/cloudstack/engine/service/api/OrchestrationService.java
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/CloudOrchestrator.java
  engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java
  engine/schema/src/main/java/com/cloud/storage/VMTemplateVO.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  server/src/main/java/com/cloud/template/TemplateManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/view/InfoCard.vue
  ui/src/views/compute/DeployVM.vue
  ui/src/views/compute/wizard/StorageRbdImageSelection.vue
  ui/src/views/infra/StorageBrowser.vue
Labels: status:has-conflicts

#512 [Mold API, UI] 20240620일자 신규 소스 병합 및 빌드 오류 수정(한글화포함)
  api/src/main/java/org/apache/cloudstack/api/command/user/volume/ListVolumesCmd.java
  engine/schema/src/main/java/com/cloud/service/dao/ServiceOfferingDao.java
  plugins/host-allocators/random/src/main/java/com/cloud/agent/manager/allocator/impl/RandomAllocator.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesServiceHelperImpl.java
  plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterResourceModifierActionWorker.java
  plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java
  plugins/user-authenticators/oauth2/src/main/java/org/apache/cloudstack/oauth2/OAuth2UserAuthenticator.java
  plugins/user-authenticators/oauth2/src/test/java/org/apache/cloudstack/oauth2/OAuth2UserAuthenticatorTest.java
  server/src/main/java/com/cloud/agent/manager/allocator/impl/FirstFitAllocator.java
  server/src/main/java/com/cloud/api/ApiServer.java
  server/src/main/java/com/cloud/api/query/QueryManagerImpl.java
  server/src/main/java/com/cloud/network/NetworkServiceImpl.java
  server/src/main/java/com/cloud/server/StatsCollector.java
  server/src/main/java/com/cloud/user/AccountManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/public/locales/ko_KR.json
  ui/src/components/view/SearchView.vue
  ui/src/views/compute/EditVM.vue
Labels: bug, customization

#513 [Mold UI] Glue 이미지로 생성시 확장모드(누락 부분 수정)
  ui/public/locales/ko_KR.json
  ui/src/views/compute/DeployVM.vue
Labels: bug, customization, localization

#514 [Mold API] 가상머신 생성시 전달되는 customParameters null 체크방식 변경 및 containsKey 방식으로 volumeId 키 존재 여부 확인
  engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/public/config.json
Labels: bug

#515 [Mold UI]기본스토리지 브라우저기능의 디스크 생성시 파라미터 전달 오류 수정
  ui/src/views/infra/StorageBrowser.vue
  ui/src/views/storage/CreateVolType.vue
Labels: bug

#518 [Mold API, UI] 20240624일자 신규 소스 반영 빌드 오류 수정
  api/src/main/java/org/apache/cloudstack/api/command/admin/offering/CreateServiceOfferingCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/ServiceOfferingResponse.java
  server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java
  ui/public/locales/ko_KR.json
Labels: bug, customization, localization
