Repository ablecloud-team/ablestack-cloud, pull requests merged in 2025-03, with the labels that each got.

#614 [Mold] 라이센스 유효기간 정보 조회에 따른 에이전트 상태 변경
  api/src/main/java/com/cloud/server/ManagementService.java
  api/src/main/java/org/apache/cloudstack/api/ApiConstants.java
  api/src/main/java/org/apache/cloudstack/api/command/admin/outofbandmanagement/LicenseCheckCmd.java
  api/src/main/java/org/apache/cloudstack/api/response/LicenseCheckerResponse.java
  plugins/metrics/pom.xml
  plugins/security/pom.xml
  server/src/main/java/com/cloud/server/LicenseCheck.java
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
  tools/apidoc/gen_toc.py
  ui/public/locales/en.json
  ui/public/locales/ko_KR.json
  ui/src/components/view/DetailsTab.vue
  ui/src/views/setting/ConfigurationTab.vue
Labels: enhancement, customization, significant

#615 [Mold API] 소스 병합 과정 plugins/metrics/pom.xml 파일 누락 부분 추가
  plugins/metrics/pom.xml
  ui/public/config.json
  ui/public/locales/ko_KR.json
Labels: bug

#617 [Mold API] 공유 파일시스템 가상머신 구성시 디스크 (sda, sdb) 순서 확인 로직 추가
  plugins/storage/sharedfs/storagevm/src/main/resources/conf/fsvm-init.yml
  tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
Labels: bug, customization, significant

#620 [Mold API] vRouter 가상머신 nic 상태 확인 누락 부분 추가
  engine/schema/src/main/resources/META-INF/db/views/cloud.domain_router_view.sql
  server/src/main/java/com/cloud/api/query/dao/DomainRouterJoinDaoImpl.java
  server/src/main/java/com/cloud/api/query/vo/DomainRouterJoinVO.java
Labels: customization

#622 [Mold API, Agent] SecurityGroup 값에 따른 도메인 xml 의 Interface값 변경, 호스트 상세 화면 라이센스 안내문구 추가
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java
  ui/public/locales/ko_KR.json
  ui/src/components/view/DetailsTab.vue
Labels: enhancement, customization, significant

#624 [Mold API] Security Group서비스가 설정된 nic를 가진 VM 일 경우 보안그룹 상세 탭 활성화 및 버그 수정
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  ui/src/components/view/DetailsTab.vue
  ui/src/views/compute/EditVM.vue
  ui/src/views/compute/InstanceTab.vue
Labels: bug, customization
