Repository ablecloud-team/ablestack-cloud, pull requests merged in 2025-04, with the labels that each got.

#626 [Mold API] 가상머신 복제기능 기능 개선( 컴퓨트 전용오퍼링 : false > 디스크오퍼링 : custom 일 경우 생성 오류)
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
Labels: bug, customization

#628 [Mold] 라이센스 시작일 체크 오류 수정
  server/src/main/java/com/cloud/server/ManagementServerImpl.java
Labels: bug

#629 [Mold Agent] AMD cpu 정보 조회시 오류 수정/ Shareable 볼륨 생성시 타입을 Raw타입으로 생성되도록 변경
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java
  plugins/hypervisors/kvm/src/main/java/org/apache/cloudstack/utils/linux/KVMHostInfo.java
  plugins/storage/sharedfs/storagevm/src/main/resources/conf/fsvm-init.yml
Labels: bug, customization

#631 [Mold API] SystemVM 템플릿 생성시 생성일자 확인되도록 수정
  tools/appliance/build.sh
  tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh
  tools/appliance/systemvmtemplate/template-base_x86_64-target_x86_64.json
Labels: customization

#633 [Mold Agent] 데이터 볼륨 가져오기, 인스턴스 가져오기시 지원되는 볼륨 항목 추가(SharedMountPoint)
  api/src/main/java/org/apache/cloudstack/storage/volume/VolumeImportUnmanageService.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckVolumeCommandWrapper.java
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCopyRemoteVolumeCommandWrapper.java
Labels: bug, customization

#634 [Mold API] vm스냅샷 복원 시 detail 정보의 'kvmStorageSnapshot' 값 제거, nic 상태 up, down시 로직수정
  server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
  ui/src/components/widgets/WallLinkUrl.vue
  ui/src/views/plugins/IFrameWall.vue
Labels: bug, customization, significant
