Repository ablecloud-team/ablestack-cloud, pull requests merged in 2025-02, with the labels that each got.

#602 [Mold UI] clvm HA 상태 체크 쉘 스크립트 버그 수정, 대시보드 2차스토리지 문구 수정('할당됨' > '사용됨')
  plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/LibvirtStoragePool.java
  scripts/vm/hypervisor/kvm/kvmheartbeat_clvm.sh
  scripts/vm/hypervisor/kvm/kvmheartbeat_rbd.sh
  ui/public/locales/ko_KR.json
  ui/src/views/dashboard/CapacityDashboard.vue
Labels: bug, customization

#604 [Mold UI] 소스 병합 후 ui 빌드 오류 수정
  ui/src/config/section/storage.js
Labels: bug

#609 [Mold API] VM스냅샷 및 복구 시 details 정보 누락되는 이슈 관련 기능 개선
  agent/src/main/java/com/cloud/agent/properties/AgentProperties.java
  server/src/main/java/com/cloud/vm/snapshot/VMSnapshotManagerImpl.java
  ui/src/config/section/network.js
Labels: bug, enhancement, customization, significant

#611 DRS 기능 수정
  server/src/main/java/com/cloud/api/query/dao/UserVmJoinDaoImpl.java
  server/src/main/java/com/cloud/resource/ResourceManagerImpl.java
  server/src/main/java/org/apache/cloudstack/cluster/ClusterDrsServiceImpl.java
  server/src/main/java/org/apache/cloudstack/ha/HAManagerImpl.java
  ui/src/views/infra/network/IpRangesTabGuest.vue
  ui/src/views/network/NicsTab.vue
Labels: enhancement, customization
